AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.5.0
  Exclude:
      - 'capybara.gemspec'

#################### Lint ################################

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
  CountComments: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/Loop:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/RedundantReturn:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*'

Style/MultilineIfModifier:
  Exclude:
    - 'spec/**/*'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Naming/AccessorMethodName:
  Exclude:
    - 'lib/capybara_page/page.rb'